config/routes.rb
Portfolio::Application.routes.draw do
  match 'contact' => 'application#contact', :as => 'contact', :via => :post
  match 'resume' => 'application#resume', :as => 'resume', :via => :get

  root :to => 'application#index'
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 
  def contact
    @message = Message.new(params[:message])
    if @message.valid?
      ContactMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :index
    end
  end

  def resume
    send_data(open("#{Rails.root}/app/assets/files/resume.pdf").read,
              :filename => "resume.pdf",
              :type => "application/pdf")
  end

  def index
  	@message = Message.new

  	render :index
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <title>
	  Ben Nelson - Software Engineer 
  </title>

 <meta name="author" content="Ben Nelson" />
 <meta name="keywords" content="software engineer" />
 <meta name="description" content="Portfolio for a software engineer." />
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_contact.html.erb
<div id="contact">
	<%= render partial: "partials/contact_form" %>
</div>

app/views/partials/_contact_form.html.erb
<div id="contactForm">

<%= form_for @message, :url => contact_path do |form| %>
 
  <fieldset class="actions">
    <%= form.submit "Send", { :class => 'btn btn-default pull-right' } %>
  </fieldset>

  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, { :class => 'form-control' } %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, { :class => 'form-control' }  %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject, { :class => 'form-control' }  %>
    </div>
    
    <div class="field contact-body">
      <%= form.label :body %>
      <%= form.text_area :body, { :class => 'form-control' }  %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/partials/_projects.html.erb
<div id="projects">


</div>